update hover list events
Azordev/did-admin-panel pull request #175
Opened 2022-09-06 03:02 UTC by luleheco22

### Description

Please include a summary of the change.

fixes # (#67 #118)

#### Screenshots
![image](https://user-images.githubusercontent.com/98011921/188538173-045a9d2c-1ba2-4092-9c55-62ce38a14d54.png)

If applicable, add screenshots about your changes

#### Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### How to test it

If applicable, describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

1. Go to '...'
2. Click on '....'
3. Scroll down to '....'

### Checklist:

- [ ] Doesn't break the current code.
- [ ] Passes linters and test, also is building.
- [ ] Doesn't have spelling or grammatical problems.
- [ ] Doesn't have unnecessary comments or debugging code.
- [ ] The branch is updated with the last dev branch changes.

2022-09-06 03:42 UTC, Luisparr14 reviewed
The function to delete the event doest work yet

2022-09-06 12:40 UTC, e-azocar commented
@angelik0828 is this the expected result?
![image](https://user-images.githubusercontent.com/61360270/188637507-e37c9a0c-9fcc-4392-a744-b9d2ab2b1b02.png)

2022-09-06 15:09 UTC, victor-heliomar commented on styles/Events.module.scss
> +  transition: .3s ease;
Please add the elements that expect to be changed https://developer.mozilla.org/en-US/docs/Web/CSS/transition-property

2022-09-06 15:10 UTC, victor-heliomar commented on styles/Events.module.scss
> +    text-shadow: 1px 1px 6px $white;
I think that text-shadow is not needed, @angelik0828 please confirm, here's some examples about what text-shadow is: https://developer.mozilla.org/en-US/docs/Web/CSS/text-shadow

2022-09-06 15:14 UTC, victor-heliomar commented on styles/Events.module.scss
> +    box-shadow: inset 0 0 20px;
If you don't add any color, box-shadow will inherit the "color" property's value, what is white currently, in this case the background is white, so the box-shadow is not visible, is the box shadow really needed?, in that case, what color should be?

here's an example of how box-shadow works:

![lastrecord](https://user-images.githubusercontent.com/66505715/188671890-1bc70c99-e2fe-43f0-9c6b-8852b70415ff.gif)

CC: @angelik0828

2022-09-06 15:16 UTC, victor-heliomar commented on styles/Events.module.scss
> +    outline-offset: 80px;
Due to you are using 0 in the alpha channel, outline-color is creating an "invisible" outline, is actually needed to have an outline so? I meant, if it's not visible, maybe can be removed these lines

![lastrecord](https://user-images.githubusercontent.com/66505715/188672407-4baf4de0-9df4-406c-b758-14e434c58c49.gif)

2022-09-06 18:18 UTC, Eghinner requested changes
Issues only recommended a hover effect to the title

2022-09-07 03:02 UTC, Eghinner commented
hmmm, take this reference https://laravel-news.com

2022-09-07 15:03 UTC, angelik0828 commented
## According to what task 67 mentions, the idea was to make the change in the side menu, place the states in the buttons. 

![image](https://user-images.githubusercontent.com/4030477/188910120-f4c9b7b7-7912-489a-9b88-f413e933f146.png)

## ✔️ But since this change has already been made and is currently needed in my browser, it looks like this:


https://user-images.githubusercontent.com/4030477/188912247-cb15b710-5d87-4bdd-a1a6-9fb1c897b340.mp4


I think it looks good

2022-09-07 15:04 UTC, angelik0828 approved these changes

2022-09-07 15:10 UTC, Luisparr14 commented
@luleheco22 the delete button does not work (issue #118), please resolve or remove from description.

2022-09-07 15:17 UTC, angelik0828 commented
## ❌ Delete button and validation modal not working

![image](https://user-images.githubusercontent.com/4030477/188915277-db137667-0c26-4426-a24e-5107975d08f7.png)

2022-09-07 17:08 UTC, Eghinner commented
@angelik0828 @luleheco22 hover dahsboard hover is resolved in another issue https://github.com/Azordev/did-admin-panel/issues/183

2022-09-07 18:52 UTC, angelik0828 commented
> @angelik0828 @luleheco22hover dashsboard hover se resuelve en otro problema #183

understood we can continue!!!

2022-09-07 18:53 UTC, angelik0828 approved these changes

2022-09-07 21:31 UTC, luleheco22 commented
I can't find a way to do the hover with the event card, it only takes them when the hover is done in the title, if you can suggest what change I can make in the code, I'll stay tuned

2022-09-08 14:01 UTC, Eghinner commented on styles/Events.module.scss
> +  .line{
move this to father simply. without hove, I mean

2022-09-08 14:01 UTC, Eghinner commented on styles/Events.module.scss
> +  .line:after {
move this to father

2022-09-08 14:01 UTC, Eghinner commented on styles/Events.module.scss
> +  .line:hover:after {
remove hover

2022-09-10 02:52 UTC, Eghinner approved these changes

2022-09-10 02:54 UTC, merged